In [2]:
#Librerias a utilizar para Machine Learning
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# La data para entrenar y predecir el modelo
dataset = pd.read_excel("dataset.xlsx", sheet_name="data")

In [4]:
dataset

Formacion Tipo de grano  Viscosidad  Longitud  Area   Caudal  Presion  \
0          A1    Grano fino    0.198514         4      3    23.0        2   
1          A2   Grano medio    0.978643         4      3   189.0        2   
2          A3  Grano grueso    0.879774         4      3   103.5        2   
3          A1   Grano medio    0.307086         4      3   386.5        2   
4          A2  Grano grueso    0.001157         4      3   393.0        2   
..        ...           ...         ...       ...    ...     ...      ...   
294        A1    Grano fino    0.772346         4      3   355.5        2   
295        A2  Grano grueso    0.055226         4      3   464.0        2   
296        A3   Grano medio    0.981936         4      3    24.5        2   
297        A1    Grano fino    0.384692         4      3   302.5        2   
298        A2   Grano medio    0.840294         4      3   298.0        2   

     Permeabilidad Tipo de permeabilidad  
0         3.043889                 Media  
1       123.309016                  alta  
2        60.704402                 Media  
3        79.125839                 Media  
4         0.303090                  Baja  
..             ...                   ...  
294     183.045990                  alta  
295      17.083267                 Media  
296      16.038291                 Media  
297      77.579625                 Media  
298     166.938446                  alta  

[299 rows x 9 columns]

In [5]:
dataset['Formacion'].unique()

array(['A1', 'A2', 'A3'], dtype=object)

In [6]:
# Identidicamos que categorias tenemos en cada columna
print('Categorias de la columna Formacion: ',dataset['Formacion'].unique())
print('Categorias de la columna Tipo de grano: ',dataset['Tipo de grano'].unique())
print('Categorias de la columna Tipo de permeabilidad: ',dataset['Tipo de permeabilidad'].unique())

Categorias de la columna Formacion:  ['A1' 'A2' 'A3']
Categorias de la columna Tipo de grano:  ['Grano fino' 'Grano medio' 'Grano grueso']
Categorias de la columna Tipo de permeabilidad:  ['Media' 'alta' 'Baja']


In [7]:
dataset['Formacion'].replace(('A1','A2','A3'),(1,2,3),inplace = True)

In [8]:
dataset

Formacion Tipo de grano  Viscosidad  Longitud  Area   Caudal  Presion  \
0            1    Grano fino    0.198514         4      3    23.0        2   
1            2   Grano medio    0.978643         4      3   189.0        2   
2            3  Grano grueso    0.879774         4      3   103.5        2   
3            1   Grano medio    0.307086         4      3   386.5        2   
4            2  Grano grueso    0.001157         4      3   393.0        2   
..         ...           ...         ...       ...    ...     ...      ...   
294          1    Grano fino    0.772346         4      3   355.5        2   
295          2  Grano grueso    0.055226         4      3   464.0        2   
296          3   Grano medio    0.981936         4      3    24.5        2   
297          1    Grano fino    0.384692         4      3   302.5        2   
298          2   Grano medio    0.840294         4      3   298.0        2   

     Permeabilidad Tipo de permeabilidad  
0         3.043889                 Media  
1       123.309016                  alta  
2        60.704402                 Media  
3        79.125839                 Media  
4         0.303090                  Baja  
..             ...                   ...  
294     183.045990                  alta  
295      17.083267                 Media  
296      16.038291                 Media  
297      77.579625                 Media  
298     166.938446                  alta  

[299 rows x 9 columns]

In [9]:
# Identidicamos que categorias tenemos en cada columna
print('Categorias de la columna Formacion: ',dataset['Formacion'].unique())
print('Categorias de la columna Tipo de grano: ',dataset['Tipo de grano'].unique())
print('Categorias de la columna Tipo de permeabilidad: ',dataset['Tipo de permeabilidad'].unique())

Categorias de la columna Formacion:  [1 2 3]
Categorias de la columna Tipo de grano:  ['Grano fino' 'Grano medio' 'Grano grueso']
Categorias de la columna Tipo de permeabilidad:  ['Media' 'alta' 'Baja']


In [10]:
dataset['Tipo de grano'].replace(('Grano fino','Grano medio','Grano grueso'),(1,2,3),inplace=True)
dataset['Tipo de permeabilidad'].replace(('alta','Media','Baja'),(1,2,3),inplace=True)

In [11]:
dataset

Formacion  Tipo de grano  Viscosidad  Longitud  Area   Caudal  Presion  \
0            1              1    0.198514         4      3    23.0        2   
1            2              2    0.978643         4      3   189.0        2   
2            3              3    0.879774         4      3   103.5        2   
3            1              2    0.307086         4      3   386.5        2   
4            2              3    0.001157         4      3   393.0        2   
..         ...            ...         ...       ...    ...     ...      ...   
294          1              1    0.772346         4      3   355.5        2   
295          2              3    0.055226         4      3   464.0        2   
296          3              2    0.981936         4      3    24.5        2   
297          1              1    0.384692         4      3   302.5        2   
298          2              2    0.840294         4      3   298.0        2   

     Permeabilidad  Tipo de permeabilidad  
0         3.043889                      2  
1       123.309016                      1  
2        60.704402                      2  
3        79.125839                      2  
4         0.303090                      3  
..             ...                    ...  
294     183.045990                      1  
295      17.083267                      2  
296      16.038291                      2  
297      77.579625                      2  
298     166.938446                      1  

[299 rows x 9 columns]

In [12]:
variables = dataset.iloc[:,[0,1,2,3,4,5,6]].values

In [13]:
variables

array([[1.00000000e+00, 1.00000000e+00, 1.98514488e-01, ...,
        3.00000000e+00, 2.30000000e+01, 2.00000000e+00],
       [2.00000000e+00, 2.00000000e+00, 9.78642988e-01, ...,
        3.00000000e+00, 1.89000000e+02, 2.00000000e+00],
       [3.00000000e+00, 3.00000000e+00, 8.79773937e-01, ...,
        3.00000000e+00, 1.03500000e+02, 2.00000000e+00],
       ...,
       [3.00000000e+00, 2.00000000e+00, 9.81936153e-01, ...,
        3.00000000e+00, 2.45000000e+01, 2.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 3.84692358e-01, ...,
        3.00000000e+00, 3.02500000e+02, 2.00000000e+00],
       [2.00000000e+00, 2.00000000e+00, 8.40294191e-01, ...,
        3.00000000e+00, 2.98000000e+02, 2.00000000e+00]])

In [14]:
resultado = dataset.iloc[:,[8]].values

In [15]:
resultado

array([[2],
       [1],
       [2],
       [2],
       [3],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [3],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [3],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [2],
    

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(variables,resultado,
                                                test_size=0.25,random_state=0)

In [19]:
len(x_test)

75

In [20]:
# Estandarizar las escalas
from sklearn.preprocessing import StandardScaler
escala_estandarizada = StandardScaler()

In [21]:
x_train= escala_estandarizada.fit_transform(x_train)
x_test = escala_estandarizada.transform(x_test)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
clasificador = KNeighborsClassifier(n_neighbors=5,metric='minkowski', p = 2)

In [24]:
clasificador.fit(x_train,y_train)

/Users/jerjesporlles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [26]:
y_pred = clasificador.predict(x_test)

In [27]:
y_pred

array([2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
       1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 2, 2, 1, 1, 2, 2, 2, 2])

In [28]:
data_pred = pd.DataFrame(y_pred)

In [33]:
data_pred.rename(columns={'y_test':'y_pred'},inplace = True)
data_pred

y_pred
0        2
1        2
2        2
3        2
4        1
..     ...
70       1
71       2
72       2
73       2
74       2

[75 rows x 1 columns]

In [34]:
y_test

array([[2],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [3],
       [2],
       [2],
       [3],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [2],
       [1],
       [2],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [3],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2]])

In [36]:
data_test = pd.DataFrame(y_test)
data_test.rename(columns={0:'y_test'},inplace = True)
data_test


y_test
0        2
1        2
2        2
3        2
4        1
..     ...
70       1
71       2
72       2
73       2
74       2

[75 rows x 1 columns]

In [37]:
df_comparacion = pd.concat([data_test, data_pred], axis=1)
df_comparacion
df_comparacion['Diferencia']=df_comparacion.y_test - df_comparacion.y_pred
df_comparacion[30:60]

y_test  y_pred  Diferencia
30       2       2           0
31       2       2           0
32       1       1           0
33       2       2           0
34       2       2           0
35       1       1           0
36       2       2           0
37       2       2           0
38       1       1           0
39       2       2           0
40       1       1           0
41       2       2           0
42       1       1           0
43       1       1           0
44       2       2           0
45       1       1           0
46       2       2           0
47       2       2           0
48       2       2           0
49       1       1           0
50       2       2           0
51       2       2           0
52       1       1           0
53       2       2           0
54       1       1           0
55       1       1           0
56       2       2           0
57       3       2           1
58       1       1           0
59       2       2           0

In [38]:
from sklearn.metrics import confusion_matrix
matris_confusion = confusion_matrix(y_test, y_pred)
matris_confusion

array([[25,  2,  0],
       [ 2, 43,  0],
       [ 0,  3,  0]])

In [39]:
sc = clasificador.score(x_test,y_test)
sc

0.9066666666666666

In [40]:
import altair as alt
alt.renderers.enable('altair_viewer', inline=True)

RendererRegistry.enable('altair_viewer')

In [41]:
grafico = alt.Chart(df_comparacion.reset_index()).mark_point(color='green').encode(
    x='index',
    y = "y_test",
    tooltip = ['index','y_test']
).interactive()

In [42]:
grafico.display()

alt.Chart(...)

In [43]:
grafico_pred = alt.Chart(df_comparacion.reset_index()).mark_square(color='red').encode(
    x= 'index',
    y = "y_pred"
).interactive()

In [44]:
grafico_pred.display()

alt.Chart(...)

In [45]:
graficos = alt.layer(grafico,grafico_pred)

In [46]:
graficos.display()

alt.LayerChart(...)